version: '2'
services:
  # Laravel Application
  users_app:
    build:
      context: ./
      dockerfile: users-app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=users_database"
  
  # Nginx Server - Laravel Server
  users_web:
    build:
      context: ./
      dockerfile: users-web.dockerfile
    working_dir: /var/www
    volumes_from:
      - users_app
    ports:
      - 8080:80
  
  # MySQL Database
  users_database:
    image: mysql:latest
    volumes:
      - users_dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=users"
      - "MYSQL_USER=devuser"
      - "MYSQL_PASSWORD=devpass"
      - "MYSQL_ROOT_PASSWORD=devpass"
    ports:
      - "33061:3306"

volumes:
  users_dbdata: